#!/bin/sh
output="$1"
cfgid="xmonad-abcfg"
barid="taffybar-abcfg"
apps="./app"
bars="./bar"
cfgs="./cfg"

lastModified () {
    stat -c '%Y' $1
}
lastModifiedIn () {
    find $1 -type f -exec stat -c '%Y' "{}" \; | sort -n | tail -1
}

max_number() {
    printf "%s\n" "$@" | sort -r | head -n1
}

appMod=$( lastModifiedIn $apps )
cfgMod=$( lastModifiedIn $cfgs )
barMod=$( lastModifiedIn $bars )
lastMod=$( max_number $appMod $cfgMod $barMod )

if [ ! -f $1 ] || [ $lastMod -gt $( lastModified $1 ) ] ; then
    cabal build "$cfgid" "$barid"
    cabal install "$cfgid" "$barid" \
        --enable-executable-stripping \
        --enable-optimization=2 \
        --installdir="./bin/" --install-method=copy \
        --overwrite-policy=always
    ln -sf "./bin/$cfgid" "$1"
fi
