#!/bin/sh
output="$1"
cfgid="xmonad-abcfg"
barid="taffybar-abcfg"
apps="./app"
bars="./bar"

lastModified () {
    stat -c '%Y' "$1"
}
lastModifiedIn () {
    find "$1" -type f -exec stat -c '%Y' "{}" \; | sort -n | tail -1
}

max_number() {
    printf "%s\n" "$@" | sort -r | head -n1
}

install_app () {
    if [ "$( lastModifiedIn "$2" )" -gt "$( lastModified "./bin/$1" )" ] ; then
        cabal install "$1" \
            --installdir="./bin/" --install-method=copy \
            --overwrite-policy=always
    fi
}

install_app $cfgid $apps
install_app $barid $bars

ln -sf "./bin/$cfgid" "$output"
