#!/bin/sh

# TODO Need also install lux
sudo apt install pasystray network-manager-gnome blueman synapse ssh-askpass-gnome

if ! command -v status-notifier-watcher; then
cabal install status-notifier-item
fi
